#! /usr/bin/env python

from Crypto.Cipher import AES
import base64
import sys
import os
import time
import re
import fcntl
import select

# ****************************************

def ask_user(title, questions):
    import dbus

    try:
        bus = dbus.SystemBus()

        remote_object = bus.get_object("org.cups.sharp.Passwd",
                                       "/org/cups/sharp/Passwd")

        iface = dbus.Interface(remote_object, "org.cups.sharp.Passwd")

        reply = iface.Ask(title, questions, timeout=3600)

        # Destroy the dbus objects ...
        del iface
        del remote_object
        del bus
    except dbus.DBusException, e:
        sys.stderr.write("ERROR: Could not ask user for authentication data.\n")
        sys.stderr.write(str(e))
        return None

    return reply

# ****************************************

def encrypt(passwd, spooltime):
    key = spooltime[-16:]
    # We need to add at least one NULL byte
    missing = 16 - len(passwd) % 16
    passwd += '\0'*missing

    aes = AES.new(key=key, mode=AES.MODE_ECB)
    encrypted = aes.encrypt(passwd)
    encrypted = base64.encodestring(encrypted).strip()

    return encrypted

jobid   = sys.argv[1]
user    = sys.argv[2]
jobname = sys.argv[3]
copies  = int(sys.argv[4])
options = sys.argv[5]
if len(sys.argv) > 6:
    filename=sys.argv[6]
    fd = open(filename)
else:
    fd = sys.stdin

spooltime=time.strftime("%a, %d %h %Y %H:%M:%S %z", time.gmtime())

option_regex = re.compile("^@PJL\s*COMMENT\s*XSHARP_(?P<option>.*?)\s*=\s*(?P<argument>.*)$")
aes_encrypt_regex = re.compile("XSHARP_AES_ENCRYPT:(?P<input>.*?):XSHARP_AES_ENCRYPT")
askpass_regex = re.compile("XSHARP_ASK_PASSWORD:(?P<label>.*?):XSHARP_ASK_PASSWORD")
askuser_regex = re.compile("XSHARP_ASK_STRING:(?P<label>.*?):XSHARP_ASK_STRING")
askpin_regex = re.compile("XSHARP_ASK_PASSCODE:(?P<label>.*?):XSHARP_ASK_PASSCODE")


# ****************************************
# Now read the file line by line, until we find the "@PJL ENTER" header.

def replace_argument(opt, arg, user_input=None):
    # OK, process the argument ...
    if user_input is None:
        input_needed = []

        for label in askpass_regex.findall(arg):
            input_needed.append((opt+'::'+label, label, 'PASSWORD'))
        for label in askuser_regex.findall(arg):
            input_needed.append((opt+'::'+label, label, 'STRING'))
        for label in askpin_regex.findall(arg):
            input_needed.append((opt+'::'+label, label, 'PASSCODE'))
        if len(input_needed) > 0:
            return None, input_needed

    arg = arg.replace("XSHARP_SPOOLTIME", spooltime)
    arg = arg.replace("XSHARP_USERNAME", user)
    arg = arg.replace("XSHARP_COPIES", str(copies))

    def askpass_replace(match):
        if user_input is not None and user_input.has_key(opt+'::'+match.group('label')):
            return user_input[opt+'::'+match.group('label')]
    arg, cnt = askpass_regex.subn(askpass_replace, arg)

    def askuser_replace(match):
        if user_input is not None and user_input.has_key(opt+'::'+match.group('label')):
            return user_input[opt+'::'+match.group('label')]
    arg, cnt = askuser_regex.subn(askuser_replace, arg)

    def askpin_replace(match):
        if user_input is not None and user_input.has_key(opt+'::'+match.group('label')):
            return user_input[opt+'::'+match.group('label')]
    arg, cnt = askpin_regex.subn(askpin_replace, arg)

    def regex_encrypt(match):
        return encrypt(match.group("input"), spooltime)
    arg, cnt = aes_encrypt_regex.subn(regex_encrypt, arg)

    return arg, None

buf = []
input_needed = None
while True:
    line = fd.readline()
    if not line:
        sys.exit(0)

    match = option_regex.match(line)
    if match:
        # Got a comment to process ...
        option = match.group("option")
        orig_arg = match.group("argument")

        arg, new_input_needed = replace_argument(option, orig_arg)
        if new_input_needed:
            if input_needed is None:
                input_needed = new_input_needed
            else:
                input_needed += new_input_needed

        if input_needed:
            buf.append((option, orig_arg))
        else:
            sys.stdout.write("@PJL SET %s=%s\n" % (option, arg))
        continue

    if line.startswith("@PJL ENTER"):
        # We may need to get input from the user ...
        if input_needed:
            user_input = ask_user(jobname, input_needed)
            # catch errors ...
            if user_input is None:
                user_input = {}
            for option, orig_arg in buf:
                if option is None:
                    sys.stdout.write(line)

                arg, new_input_needed = replace_argument(option, orig_arg, user_input)
                sys.stdout.write("@PJL SET %s=%s\n" % (option, arg))

        sys.stdout.write(line)
        break

    if input_needed:
        buf.append((None, line))
    else:
        sys.stdout.write(line)

in_fd = sys.stdin.fileno()
fl = fcntl.fcntl(in_fd, fcntl.F_GETFL)
fcntl.fcntl(fd, fcntl.F_SETFL, fl | os.O_NONBLOCK)

out_fd = sys.stdout.fileno()
fl = fcntl.fcntl(out_fd, fcntl.F_GETFL)
fcntl.fcntl(fd, fcntl.F_SETFL, fl | os.O_NONBLOCK)


buf = []

out_open = True
in_open = True

while (out_open and len(buf) > 0) or (out_open and in_open):
    poll = select.poll()

    if out_open:
        if len(buf) > 0:
            mask = select.POLLOUT | select.POLLHUP | select.POLLERR
        else:
            mask = select.POLLHUP | select.POLLERR
        poll.register(out_fd, mask)

    if in_open:
        if len(buf) < 100:
            mask = select.POLLIN | select.POLLHUP | select.POLLERR
        else:
            mask = select.POLLHUP | select.POLLERR
        poll.register(in_fd, mask)

    res = poll.poll()

    for fd, signal in res:
        if signal & (select.POLLHUP | select.POLLERR):
            if fd == in_fd:
                # read the rest of the input.
                buf.append(sys.stdin.read())
                in_open = False
            elif fd == out_fd:
                out_open = False
        else:
            if fd == in_fd:
                data = sys.stdin.read()
                # recieved EOF, do not keep reading.
                if len(data) == 0:
                    in_open = False
                buf.append(data)
            elif fd == out_fd:
                sys.stdout.write(buf.pop(0))
        break


